package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            password("octopus_apikey", "credentialsJSON:35246890-0122-4a3b-a371-5a0fa88850c2", label = "octopus_apikey", description = "Octopus API Key", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
    }
}
